CC=gcc
CXX=g++
threads_tasks: threads_tasks.cxx
	${CXX} threads_tasks.cxx -o threads_tasks.o -pthread  
threads_mutex: threads_mutex.cxx
	${CXX} threads_mutex.cxx -o threads_mutex.o -pthread -std=c++14
future_demo: future_demo.cxx
	${CXX} future_demo.cxx -o future_demo.out -pthread -std=c++14
future_packaged: future_packaged.cxx
	${CXX} future_packaged.cxx -o future_packaged.out -pthread -std=c++14
lock_guard_demo: lock_guard_demo.cxx
	${CXX} lock_guard_demo.cxx -o lock_guard_demo.out -pthread -std=c++14
lock_guard_example: lock_guard_example.cxx
	${CXX} lock_guard_example.cxx -o lock_guard_example.out -pthread -std=c++14
lock_example: lock_example.cxx
	${CXX} lock_example.cxx -o lock_example.out -pthread -std=c++14
try_lock_for_example: try_lock_for_example.cxx
	${CXX} try_lock_for_example.cxx -o try_lock_for_example.out -pthread -std=c++14






