CC=gcc
CXX=g++
threads_tasks: threads_tasks.cxx
	${CXX} threads_tasks.cxx -o threads_tasks.o -pthread  
threads_mutex: threads_mutex.cxx
	${CXX} threads_mutex.cxx -o threads_mutex.o -pthread -std=c++11
future_demo: future_demo.cxx
	${CXX} future_demo.cxx -o future_demo.out -pthread -std=c++11
future_packaged: future_packaged.cxx
	${CXX} future_packaged.cxx -o future_packaged.out -pthread -std=c++11





