CC=gcc
CXX=g++
threads_demo: threads_demo.cc
	${CXX} threads_demo.cc -o threads_demo.o -pthread -std=c++11 
threads_demo1: threads_demo1.cc
	${CXX} threads_demo1.cc -o threads_demo1.o -pthread -std=c++11
future_demo: future_demo.cxx
	${CXX} future_demo.cxx -o future_demo.out -pthread -std=c++11
future_packaged: future_packaged.cxx
	${CXX} future_packaged.cxx -o future_packaged.out -pthread -std=c++11





